# Herb configuration
# Documentation: https://herb-tools.dev

version: 0.8.5

files:
  include:
    - "app/views/**/*.erb"
  exclude:
    - "node_modules/**"
    - "vendor/**"
    - "coverage/**"
    - "tmp/**"

linter:
  enabled: true
  rules:
    erb-prefer-image-tag-helper:
      enabled: false
    html-no-underscores-in-attribute-names:
      enabled: false

formatter:
  enabled: false
  indentWidth: 2
  maxLineLength: 80
